version: '3'
services:

  management:
    image: thomasmarquesbr/flyiot_management
    container_name: management
    ports:
      - 5002:5002
    environment:
      - HOSTNAME=${HOSTNAME}
    command: ${HOSTNAME}
    depends_on:
      - discovery
      - data_management

  mongodb:
    image: mvertes/alpine-mongo
    container_name: database
    ports:
      - 27017:27017
#    volumes:
#      - ./../data_management_service/db:/data/db

  data_management:
    image: thomasmarquesbr/flyiot_datamanagement
    container_name: data_management
    ports:
      - 5001:5001
    environment:
      - HOSTNAME=${HOSTNAME}
    command: ${HOSTNAME}
    depends_on:
      - mongodb
      - discovery

  discovery:
    image: thomasmarquesbr/flyiot_discovery
    container_name: discovery
    ports:
      - 5000:5000
    environment:
      - HOSTNAME=${HOSTNAME}
    command: ${HOSTNAME}
#    depends_on:
#      - management
#      - data_management

#networks:
#  dev-network:
#    driver: bridge
