FlyIoTL:

  things:

    - thing: myPlayer
      type: mediaPlayer
      params: ['mediaurl']
      requirements:
        codecs: ['h264', 'aac', 'mp3?']
        formats: ['ts']
        protocols: ['dash', 'rtsp']

    - thing: myTouchSurface
      type: touchSurface
      requirements:
        gestures: [ 'swipeUp', 'swipeDown', 'swipeLeft', 'swipeRight' ]
        multitouch: true

    - thing: myLed
      type: ledRGB
      params: ['color']

  workflows:

    - workflow: w1
      when:
        - myTouchSurface: 'swipeUp'
      do:
        - myPlayer: start
          mediaurl: 'https://www.radiantmediaplayer.com/media/bbb-360p.mp4'
        - myLed: start
          color: '#ff000f'

    - workflow: w2
      when:
        - myTouchSurface: 'swipeDown'
        - w1: starts
      do:
        - myPlayer: stop
        - myLed: stop