version: '3'
services:

  discovery:
    build:
      dockerfile: ./discovery.dockerfile
      context: .
    image: middleware/discovery_img
    container_name: discovery
    # ports:
      # - "80:80"
    networks:
      - dev-network
    volumes:
      - /home/thomas/Projetos/middleware/discovery_service/:/usr/src/app/

  management:
    build:
      dockerfile: ./management.dockerfile
      context: ../management_service/
    image: middleware/management_img
    container_name: management
    networks: 
      - dev-network
    depends_on:
      - "discovery"
    volumes:
      - /home/thomas/Projetos/middleware/management_service/:/usr/src/app/

  mongodb:
    image: mvertes/alpine-mongo
    container_name: database
    ports:
      - 27017:27017
    networks: 
      - dev-network
    volumes: 
      - /home/thomas/Projetos/middleware/data_management_service/db:/data/db

  data_management:
    build:
      dockerfile: ./datamanagement.dockerfile
      context: ../data_management_service
    image: middleware/data_management_img
    container_name: data_management
    networks: 
      - dev-network
    depends_on:
      - "mongodb"
      - "discovery"
    volumes:
      - /home/thomas/Projetos/middleware/data_management_service/:/usr/src/app/

networks: 
  dev-network:
    driver: bridge
